### ISSUE TITLE
Incorrect backend_url value for Reading library on the search-library-catalogue route

### ISSUE THREAD

**Issue by uzakov** [alphagov/router#158]
When searching for my local library catalogue ([https://www.gov.uk/search-library-catalogue/reading](https://www.gov.uk/search-library-catalogue/reading)) the webpage it takes you to is http://reading-hip.epixtech.co.uk/ipac20/ipac.jsp?profile= which can't be reached.
epixtech.co.uk seems to be abandoned and not used anymore. Last update according to whois was back in 2015, no DNS data.

This seems to be the most relevant repository to report this issue to.

**Comment by cbaines** [comment]
Hi @uzakov 

So, this will actually be an issue with the data maintained by the Local Links Manager app (https://github.com/alphagov/local-links-manager/ ). I'll have a look at reporting this internally, but you can also use the support form here https://www.gov.uk/contact/govuk

I'll close this now, as this repository isn't really the place to track this issue.

Thanks,

Chris

**Comment by nicholsj** [comment]
FYI that link has now been updated (although it could take a while for caches to clear etc)

**Comment by uzakov** [comment]
Thanks everyone!
