### ISSUE TITLE
Integration tests fail (in GOV.UK Docker)

### ISSUE THREAD

**Issue by benthorner** [alphagov/router#210]
This regression was introduced in: https://github.com/alphagov/router/commit/678ef634657885e4eb552954ef89dcc29b47193c

It looks like the new code requires the Mongo DB to be a replica set. The test failures don't give any insight into the cause of the error, probably because the router is being run as a separate binary, and doesn't seem to be logging its errors anywhere.

Example failure:

```
Redirection
/go/src/github.com/alphagov/router/integration_tests/redirect_test.go:10
  prefix redirects
  /go/src/github.com/alphagov/router/integration_tests/redirect_test.go:71
    should not preserve the query string when redirecting if specified [It]
    /go/src/github.com/alphagov/router/integration_tests/redirect_test.go:106

    Expected
        <string>: 
    to equal
        <string>: /baz

    /go/src/github.com/alphagov/router/integration_tests/redirect_test.go:108
```

List of more failures:

```

[Fail] Redirection prefix redirects [It] should not preserve the query string when redirecting if specified 
/go/src/github.com/alphagov/router/integration_tests/redirect_test.go:108

[Fail] Redirection prefix redirects [It] should contain cache headers of 30 mins 
/go/src/github.com/alphagov/router/integration_tests/redirect_test.go:113

[Fail] Redirection prefix redirects [It] should handle path-preserving redirects with special characters 
/go/src/github.com/alphagov/router/integration_tests/redirect_test.go:129

[Fail] Redirection external redirects exact redirect [It] should redirect to the external URL 
/go/src/github.com/alphagov/router/integration_tests/redirect_test.go:146

[Fail] Redirection external redirects exact redirect [It] should not preserve the query string by default 
```

I get a more informative error if I start the app manually:

```
router-app_1                                | 2021/05/14 08:39:53 router: listening for refresh on :3055
router-app_1                                | 2021/05/14 08:39:53 router: starting self-update process, polling for route changes every 2s
router-app_1                                | 2021/05/14 08:39:55 router: couldn't get replica set status from MongoDB, skipping update (error: not running with --replSet)
```

I tried to fix this manually in GOV.UK Docker, and while the app started without errors, the integration tests are still failing for some unknown reason, due to the logs being mysteriously absent.

I think this is equally an issue for anywhere trying to develop this repo without GOV.UK Docker, since the README doesn't provide any specialist instructions about installing or configuring MongoDB.

I'd say this issue is resolved when:

- We can see error logs from the router when we run integration tests. It may be these are being output somewhere; we could document where they're going, or change the file path so it's more obvious.

- I can run integration tests in GOV.UK Docker and they pass, with the reasonable exception of the performance tests.

**Comment by benthorner** [comment]
Note that the router build with GOV.UK Docker has been broken for other reasons, as well, so you may need to pull the latest version after the final fix has been added: https://github.com/alphagov/govuk-docker/pull/489.

**Comment by sengi** [comment]
Dup of https://github.com/alphagov/govuk-docker/issues/591.

It doesn't look like anyone's actually needed to run Router in govuk-docker in the past 3 years or so. We hope to start replacing govuk-docker use cases with Kubernetes soon, so it'll become possible to run end-to-end tests locally.
